---
- name: Check System Disk Space
  hosts: all
  vars:
    minimum_diskspace: 10
    win_disk_facts:
      filter:
        - partitions
        - volumes
    
  tasks:        
    - name: "Ensure that minimum free space is 10GB"
      assert:
        that: item.2.size_remaining/1024 > minimum_diskspace
        msg: "Remaining disk space has reached {{ item.2.size_remaining }} need 10GB to proceed."
      when: item.1.drive_letter == 'C'
      loop: "{{ ansible_disks | subelements('partitions') }}"
      register: system_diskspace
      
