---
- name: Check System Disk Space
  hosts: all
  vars:
    minimum_diskspace: 10
    win_disk_facts:
    
  tasks:        
    - name: "Ensure that minimum free space is 10GB"
      debug:
        msg: "{{ item.1.drive_letter }} {{ item.2.size_remaining }}"
      loop: "{{ ansible_facts.disks | subelements('partitions') }}"
