---
- hosts: all
  gather_facts: no

  tasks:
  - name: Get disk facts
    win_disk_facts:

  - name: Set partition_list
    set_fact:
      partition_list: "{{ partition_list | default([]) + [{ 'partition': item.0.drive_letter, 'free': item.1.size_remaining/1024|pow(3)|float)|round(1) }] }}"
    loop: "{{ disk.partitions | subelements('volumes') }}"

  - name: Partition
    debug:
      msg: "Partition {{ item.partition }} - {{ item.free }}"
    loop: "{{ partition_list }}"

    vars:
      disk: '{{ ansible_facts.disks[0] }}'

      
      vol_part_free: '{{ disk.partitions[1].volumes[0].size_remaining/1024|pow(3)|float)|round(1)  }}' 
