---

- name: Check System Disk Space
  hosts: all
   
  vars:
    minimum_diskspace: 10
      
  tasks:
    - name: Get disk facts
      win_disk_facts:
      
    - name: "Ensure that minimum free space on {{ disk }} is 10GB"
      assert:
        that: item.disk.size_remaining/1024 > minimum_diskspace
        msg: 'Remaining disk space has reached {{ free_diskspace }} need 10GB to proceed.'
      when: item.drive_letter == "C"
      loop: "{{ item.disk }}"
      register: system_diskspace
