---
- name: Check System Disk Space
  hosts: all
  vars:
    minimum_diskspace: 10240
    win_disk_facts:

  tasks:  
     - name: "Ensure that minimum free space is 10GB"
       assert:
         that: item.2.size_remaining > minimum_diskspace
         msg: "Remaining disk space more than 10GB, proceed."
       when: item.1.drive_letter == "C"
       loop: "{{ ansible_disks (['partitions', 'volumes'])|list }}"
       register: system_diskspace
      
