---
- name: Check System Disk Space
  hosts: all
  vars:
    minimum_diskspace: 10
    
  tasks:
    - name: Get disk facts
      win_disk_facts:     
    - name: Output disks
      debug:
        var: ansible_facts.disks.partitions

