---

- name: Check System Disk Space
  hosts: all
   
  vars:
    minimum_diskspace: 10
      
  tasks:
    - name: Get disk facts
      win_disk_facts:
      
    - name: "Ensure that minimum free space on C: drive is 10GB"
      assert:
        that: item.size_remaining/1073741824 > minimum_diskspace
        msg: 'Remaining disk space has reached {{ item.size_remaining | filesizeformat }} need 10GB to proceed.'
      when: item.drive_letter == "C"
      loop: "{{ item.drive_letter }}"
      register: system_diskspace
