---
- name: Check System Disk Space
  hosts: all
  vars:
    minimum_diskspace: 10
    
  tasks:
    - name: Get disk facts
      win_disk_facts:     
    - name: Output disks
      debug:
        msg: "Disk {{ item.0.guid }} - Drive {{ item.1.drive_letter }}"
      loop: "{{ ansible_facts.disks | subelements('partitions') }}"

