---
- name: Check System Disk Space
  hosts: all
  vars:
    minimum_diskspace: 10240
    win_disk_facts:

  tasks:  
     - name: "Ensure that minimum free space is 10GB"
       assert:
         that: item.1.size_remaining > minimum_diskspace
         msg: "Remaining disk space more than 10GB, proceed."
       when: item.0.drive_letter == "C"
       with_subelements:
         - "{{ ansible_disks.partitions }}"
         - "{{ ansible_disks.volumes }}"
       register: system_diskspace
      
