---
- name: Check System Disk Space
  hosts: all
  vars:
    minimum_diskspace: 10240
    win_disk_facts:
    register: disk_facts

  tasks:  
     - name: "Ensure that minimum free space is 10GB"
       assert:
         that: ansible_facts.disks[0].size_remaining > minimum_diskspace
         msg: "Remaining disk space more than 10GB, proceed."
       when: ansible_facts.disks[0].drive_letter == "C"
       register: system_diskspace
      
