---
- name: Check System Disk Space
  hosts: all
  vars:
    minimum_diskspace: 10
    
  tasks:
    - name: Get disk facts
      win_disk_facts:
       
    - name: "Ensure that minimum free space on C drive is 10GB"
      vars:
        disk: '{{ ansible_facts.ansible_disks|selectattr("system_disk")|first }}'
      assert:
        that: ansible_facts.disk.volumes.size_remaining/1024 > minimum_diskspace
        msg: 'Remaining disk space has reached {{ ansible_facts.disk.volumes.size_remaining/1024 | filesizeformat }} need 10GB to proceed.'
      when: ansible_facts.disk.partitions.drive_letter == "C"
      loop: "{{ ansible_facts.disk.partitions.drive_letter }}"
      register: system_diskspace
