---
- hosts: all
  gather_facts: yes

  tasks:
  - name: Set partition_list
    
    set_fact:
      partition_list: "{{ partition_list | default([]) + [{ 'partition': item.0.drive_letter, 'used': item.1.size_remaining/1024|pow(3)|float)|round(1) }] }}"
    loop: "{{ disks.partitions | subelements('volumes') }}"

  - name: Partition
    debug:
      msg: "Partition {{ item.partition }} - {{ item.used }}"
    loop: "{{ partition_list }}"
