---
- name: Check System Disk Space
  hosts: all
  vars:
    minimum_diskspace: 10
    win_disk_facts:
      filter:
        - partitions
        - volumes
    
  tasks:        
    - name: "Ensure that minimum free space is 10GB"
      debug:
        msg: "{{ ansible_disks }}"
      
