---
- hosts: all
  strategy: free
  gather_facts: no
  vars:
    win_update_categories:
        - CriticalUpdates
        - SecurityUpdates
        - UpdateRollups
        - Updates


  tasks:
    - block:
        - name: Checking for Available Windows Updates
          win_updates:
            category_names: "{{ win_update_categories }}"
            state: searched
          async: 180
          poll: 10
          register: available_updates
          become: yes
          become_method: runas
          become_user: SYSTEM

    - block:
        - name: Install Available Updates
          win_updates:
            category_names: "{{ win_update_categories }}"            
          register: installed_updates
        - name: Reboot, only if required.
          win_reboot:
          when: installed_updates.reboot_required
          register: reboot_status
      when: (available_updates.found_update_count|int >= 1)
   
    - block:
        - debug:
            msg: |
              Host {{ inventory_hostname }} has been patched and rebooted. {{ installed_updates.installed_update_count }} updates were installed. The updates installed were:
              
              {% for key, value in installed_updates.updates.items() %}
                - {{ value.categories }} : {{ value.title }}
              {% endfor %}
          when: (available_updates.found_update_count|int >= 1)  
           
        - debug:    
            msg: |
              Host {{ inventory_hostname }} has {{ available_updates.found_update_count }} updates available.
          when: (available_updates.found_update_count|int < 1)    